name: Pull and Test
on: [push]
jobs:
  mac_docker:
    runs-on: macos-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - name: Hello World Docker
        run: |
         set -x
         docker version
         docker run --rm hello-world
      - name: Pull Docker Container
        run: docker pull python
