name: Pull and Test
on: [ push ]
jobs:
  linux_docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - name: Hello World Docker
        run: |
          set -x
          docker version
          docker run --rm hello-world
